[book]
authors = ["Fitz (Philip Fitzsimons)"]
language = "en"
src = "src"
title = "Well-Architected 2"
description = "A modern approach to technology architecture"

[build]
build-dir = "public"

[output.html]
additional-js = ["theme/footer.js"]